### ISSUE TITLE
Timeline for releasing the r50-detr pretrained weight:

### ISSUE THREAD

**Issue by jasminethurder** [xingaoli/DP-HOI#1]
Thank you for your excellent work! May I ask when you plan to release the weight files for r50-detr? I am very interested in your work and would like to use your weight files in my own work. Thanks again."

**Comment by xingaoli** [comment]
Thank you very much for your interest in our work！ The pre-training weights for the r50-detr can already be downloaded from https://drive.google.com/file/d/1DYBY8wHDGDPh9pyvxBewTqmpbztAzazb/view.
