### ISSUE TITLE
Timeline for testing code and full training code

### ISSUE THREAD

**Issue by kongzihan** [xingaoli/DP-HOI#2]
Impressive and innovative work! Could you please share any information on the expected release timeline for testing code and full training code? Having access to these would be immensely beneficial. Thank you for your contributions and looking forward to the update.

**Comment by zlli3** [comment]
Thank you very much for your interest in our work. We are currently busy with a recent significant DDL. We plan to publish our code by the end of next month.

**Comment by kongzihan** [comment]
您的邮件已经收到！
