### ISSUE TITLE
About resnet50 weights for vcoco dataset

### ISSUE THREAD

**Issue by soberguo** [xingaoli/DP-HOI#3]
Thank you very much for your excellent work and open source your code. I would like to ask you which is the pre-trained weight of resnet50 for vcoco dataset

**Comment by zlli3** [comment]
The pre-trained weight of resnet50 for vcoco dataset can be [download](https://drive.google.com/file/d/1DYBY8wHDGDPh9pyvxBewTqmpbztAzazb/view?usp=sharing) here. You can start fine-tuning on vcoco with the following commands.
```
python ./tools/convert_parameters.py \
        --finetune_model gen \
        --load_path params/dphoi_res50_3layers.pth \
        --save_path params/dphoi_res50_gen_vcoco.pth \
        --dataset vcoco \
        --num_queries 64
sh ./scripts/finetune/gen-vlkt/train_vcoco.sh
```

**Comment by soberguo** [comment]
Thanks for your reply, is there any VCOCO pre-trained weights for two-stage method (such as upt)?

**Comment by zlli3** [comment]
> Thanks for your reply, is there any VCOCO pre-trained weights for two-stage method (such as upt)?

You can refer to the original two-stage method (such as [upt](https://github.com/fredzzhang/hicodet/tree/vcoco))  and replace the original DETR parameters with the pre-trained [weights](https://drive.google.com/file/d/1DYBY8wHDGDPh9pyvxBewTqmpbztAzazb/view) from DP-HOI.
