### ISSUE TITLE
Download and unzip the processed annotations.zip

### ISSUE THREAD

**Issue by ha1ha2hahaha** [xingaoli/DP-HOI#5]
the VG dataset 
Download and unzip the processed [annotations.zip](https://drive.google.com/file/d/1IotuJxE8-XXrgQng_TuOSRvDGWKGA8p4/view?usp=sharing)  is not the annotations.zip file，could you provide this file in DP-HOI/data/caption/annotations folder

**Comment by zlli3** [comment]
The processed [annotations.zip](https://drive.google.com/file/d/14QBALW-aAfiSbP3sXn6suEGKsT2FmCmh/view?usp=sharing) is updated.
